# Generated by Django 2.2.2 on 2019-10-08 16:51

import datetime
from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('art_id', models.AutoField(primary_key=True, serialize=False)),
                ('art_title', models.CharField(max_length=100)),
                ('art_desc', models.CharField(max_length=500)),
                ('created_at', models.DateField(default=datetime.datetime.now)),
            ],
            options={
                'db_table': 'article',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('cat_id', models.AutoField(primary_key=True, serialize=False)),
                ('cat_name', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('city_id', models.AutoField(primary_key=True, serialize=False)),
                ('city_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'city',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('feedback_id', models.AutoField(primary_key=True, serialize=False)),
                ('feedback_name', models.CharField(max_length=50)),
                ('feedback_email', models.EmailField(max_length=100, unique=True)),
                ('feedback_mnum', phone_field.models.PhoneField(max_length=12)),
                ('feedback_feedback', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'feedback',
            },
        ),
        migrations.CreateModel(
            name='MasterUsers',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=50)),
                ('user_email', models.EmailField(max_length=100, unique=True)),
                ('user_pass', models.CharField(max_length=50)),
                ('user_type', models.CharField(max_length=10)),
                ('sec_que', models.IntegerField()),
                ('sec_ans', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'masterusers',
            },
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'register',
            },
        ),
        migrations.CreateModel(
            name='States',
            fields=[
                ('state_id', models.AutoField(primary_key=True, serialize=False)),
                ('state_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'state',
            },
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('subcat_id', models.AutoField(primary_key=True, serialize=False)),
                ('subcat_name', models.CharField(max_length=300)),
                ('subcat_cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='find_tutor.Category')),
            ],
            options={
                'db_table': 'subcategory',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('sub_id', models.AutoField(primary_key=True, serialize=False)),
                ('sub_name', models.CharField(max_length=300)),
                ('sub_subcat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='find_tutor.Subcategory')),
            ],
            options={
                'db_table': 'subject',
            },
        ),
        migrations.CreateModel(
            name='Tutor_Registration',
            fields=[
                ('tutor_id', models.AutoField(primary_key=True, serialize=False)),
                ('tutor_fname', models.CharField(max_length=50)),
                ('tutor_lname', models.CharField(max_length=50)),
                ('tutor_mnum', phone_field.models.PhoneField(max_length=12)),
                ('tutor_gender', models.CharField(max_length=5)),
                ('tutor_dob', models.DateField()),
                ('tutor_qualification', models.CharField(max_length=20)),
                ('tutor_experience', models.IntegerField()),
                ('tutor_aboutme', models.CharField(max_length=200)),
                ('tutor_propic', models.ImageField(upload_to='upload/')),
                ('tutor_status', models.BooleanField(default=True)),
                ('tutor_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='find_tutor.City')),
                ('tutor_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='find_tutor.States')),
                ('tutor_sub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='find_tutor.Subject')),
                ('tutor_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='find_tutor.MasterUsers')),
            ],
            options={
                'db_table': 'tutor_registration',
            },
        ),
        migrations.CreateModel(
            name='TutorXsubject',
            fields=[
                ('tutsub_id', models.AutoField(primary_key=True, serialize=False)),
                ('tutsub_sub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='find_tutor.Subject')),
                ('tutsub_tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='find_tutor.Tutor_Registration')),
            ],
            options={
                'db_table': 'tutorXsubject',
            },
        ),
        migrations.CreateModel(
            name='Student_Registration',
            fields=[
                ('stud_id', models.AutoField(primary_key=True, serialize=False)),
                ('stud_fname', models.CharField(max_length=50)),
                ('stud_lname', models.CharField(max_length=50)),
                ('stud_mnum', phone_field.models.PhoneField(max_length=12)),
                ('stud_gender', models.CharField(max_length=6)),
                ('stud_dob', models.DateField()),
                ('stud_propic', models.ImageField(upload_to='upload/')),
                ('stud_status', models.BooleanField(default=True)),
                ('stud_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='find_tutor.City')),
                ('stud_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='find_tutor.States')),
                ('stud_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='find_tutor.MasterUsers')),
            ],
            options={
                'db_table': 'student_registration',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('que_id', models.AutoField(primary_key=True, serialize=False)),
                ('que_que', models.CharField(max_length=300)),
                ('que_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='find_tutor.MasterUsers')),
            ],
            options={
                'db_table': 'question',
            },
        ),
        migrations.CreateModel(
            name='Notifaction',
            fields=[
                ('not_id', models.AutoField(primary_key=True, serialize=False)),
                ('not_notif', models.CharField(max_length=300)),
                ('not_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='find_tutor.MasterUsers')),
            ],
            options={
                'db_table': 'notification',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('msg_msg', models.CharField(max_length=300)),
                ('msg_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='find_tutor.MasterUsers')),
            ],
            options={
                'db_table': 'message',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('mat_id', models.AutoField(primary_key=True, serialize=False)),
                ('mat_subject', models.CharField(max_length=50)),
                ('mat_doc', models.FileField(upload_to='documents/')),
                ('mat_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='find_tutor.MasterUsers')),
            ],
            options={
                'db_table': 'material',
            },
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('flw_id', models.AutoField(primary_key=True, serialize=False)),
                ('flw_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='find_tutor.MasterUsers')),
            ],
            options={
                'db_table': 'follow',
            },
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='find_tutor.States'),
        ),
        migrations.CreateModel(
            name='ArticleXcomment',
            fields=[
                ('artxcmt_id', models.AutoField(primary_key=True, serialize=False)),
                ('artxcmt_cmt', models.CharField(max_length=500)),
                ('artxcmt_art', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='find_tutor.Article')),
                ('artxcmt_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='find_tutor.MasterUsers')),
            ],
            options={
                'db_table': 'articleXcomment',
            },
        ),
        migrations.CreateModel(
            name='Articlelike',
            fields=[
                ('artlike_id', models.AutoField(primary_key=True, serialize=False)),
                ('artlike_art', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='find_tutor.Article')),
                ('artlike_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='find_tutor.MasterUsers')),
            ],
            options={
                'db_table': 'articlelike',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='art_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='find_tutor.MasterUsers'),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('ans_id', models.AutoField(primary_key=True, serialize=False)),
                ('ans_ans', models.CharField(max_length=500)),
                ('ans_image', models.ImageField(upload_to='upload/')),
                ('ans_que', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='find_tutor.Question')),
                ('ans_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='find_tutor.MasterUsers')),
            ],
            options={
                'db_table': 'answer',
            },
        ),
    ]
