# Generated by Django 2.2.2 on 2019-10-09 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('find_tutor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_registration',
            name='stud_subcat_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='find_tutor.Subcategory'),
            preserve_default=False,
        ),
    ]
